var GAME_LEVELS = [
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                xxxxxxvxxxxxx                   ",
   "                                                                                ",
   "                                                                                ",
   "                                                     o o                        ",
   "                                                                                ",
   "                                                 xxxx   xxxx                    ",
   "                                         o          x!!!x         o             ",
   "                                        xxx         xxxxx       xxxxx           ",
   "                                                                            xx  ",
   "                                         oo                  o               x  ",
   "                                       xxxxxx               xxx              x  ",
   " xxxx              o o                                oo                     x  ",
   " x          o     xxxxx     o                    oo  xxxx                    x  ",
   " x @      xxxxx           xxxxx            z    xxxx             sssss       x  ",
   " xxxxxx                           xxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!!!!!x           x!!!!!!!!!!!!x                    ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!!!!!x           x!!!!!!!!!!!!x                    ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xxxxxxxxxxxxxx                    ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!!x                       xxxxxxx!!!!                                x!x  ",
   "                                      x!!!x                             xxxx!                                x!x  ",
   "                                      x!!!xxxxxxxxx                        xx!                               x!x  ",
   "                                      x!!!!!!!!!!!!x                        x!                              =x!x  ",
   "                                       xxxxxxxxxx!!x                         v                    o   o   o  x!x  ",
   "                                                x!!x               o   o                                    xx!x  ",
   "                                                 xvx                             xxxxxx      =xxxxxxxxxxxxxxx!!x  ",
   "                                                                   x   x                 !!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx                          !xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!xxxxx          vv                       ",
   "                                             oo                xxxx!!!!!xxxx                                      ",
   "                                            xxxx     x            xxxxxxx        xxx         xxx                  ",
   "                                               x!!!xxx                           xxx         xxx                  ",
   "                                     xxx       x!!!!!x                             x   x     x                    ",
   "                xxxxxxx                        x!!!!!x                             x         x                    ",
   "               xx!!!!!xx                   xxxxx!!!!!x                             xx        x                    ",
   "              xx!!!!!!!xx      o       o       !!!!!!x             xxx   xxx       x         x                    ",
   "                xxxvxxx                       !!!!!!!x       oo    x x   x x!!!!!!!x         x                    ",
   "                              xxx     xxx    !!xxxxxxx     xxxxxx    x   x!!!xxxvxxxxx       x                    ",
   "                                             !!x    ox               x   xxxxx               x                    ",
   "     @                                      !!!x     x               x                       x                    ",
   "xxxxxxx                           xxxx     !!!!x     x               x           xxxxxx      x                    ",
   "      x                            o      !!!!!x z   x               x     o   o             x                    ",
   "      x xxxx    oo             xx     xxx!!!!!!xxx    x!!!!!!!!!!    xx     =             xxxx                    ",
   "      x        xxxx   oo    =xx       xxxxxxxxxx     x!!!!!!!xx!!    xxxxxxxxxxxxxxxx  o o  xx                    ",
   "      x              xxxx    x    o                 xx!!!!!!xx!!!                   xx     xx                     ",
   "      x!!!!!!!!!!!!!!!!!!!!!!x   xxxx              xx!!!!!!xx!!!!                    xxxxxxx                      ",
   "      x!!!!!!!!!!!!!!!!!!!!!!xxss     xxxxxxxxxxxxxx!!!!!!xx!!!!!                                                 ",
   "      x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!  !!                                                 ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xx!    !!                                                 "],
   ["                                      x!!!!x                                                                   ",
    "                                      x!!!!x                                                                  ",
    "                                      x!!!!x                                                                  ",
    "                                      x!!!!x                                                                  ",
    "                                      x!!!!x               oo                                                 ",
    "                                      x!!!!x              xxxx                                                ",
    "                                      x!!!!x               sss                                                ",
    "                                      x!!!!x      xx     o sxs        xx                                      ",
    "                                      x!!!!x            xxxxxs      xxxx                                      ",
    "                                      x!!!!x      oo        xxxx       x       xxx                            ",
    "                                      x!!!!x     xxxx    xxxx    oo  = x      x!!!x                           ",
    "                                      x!!!!x                xxxxxxxxxxxx       xvx                            ",
    "                                      x!!!!xxxxx             x                                                ",
    "                                      x!!!!x          xxxxxxxx              x x                               ",
    "                                      x!!!!x          x                    x!!!x                              ",
    "                                      x!!!!x        xxx                     xvx                               ",
    "                                      x!!!!xxxx       x                                                       ",
    "                                      x!!!!x =        x            xxx                                        ",
    "                                      x!!!!x          x           x!!!x                                       ",
    "                                      x!!!!x       xxxx     o      xxx       xxx                              ",
    "                                      x!!!!x       = =x                     x!!!x                             ",
    "                                      x!!!!x          x     x                xxv        xxx                   ",
    "                             xxxxxxxxxx!!!!xxxx       x              xx                x!!!x                  ",
    "                 xxx         xxxxxxxxxx!!!!x     o o  x!!!!!!!!!!!!!!x                   vx                   ",
    "                 x x!!!!!!!!!xxxxxxxxxxxvxxx          x!!!!!!!!!!!!!!x                                        ",
    "                   x!!!!!!!!!xx           x       xxxxxxxxvxxxvvxxvxxxxxxx                                    ",
    "                   x!!!!!!!!!xx     o     x     xxx                      x           xxx                      ",
    "  xxx              xxxxxxxxxxxx     x     x                              x          x!!!x                xxx  ",
    "  x x                         x    xx    xx                              x           xvx                 x x  ",
    "  x                           x   oxx     xxxxxxx                        xxxxx                             x  ",
    "  x                           x   xxxx    x                              x!!!x                             x  ",
    "  x                           xx          x                              x!!!x                             x  ",
    "  x                                     xxx        xxxx      xxxx      xxx!!!x                             x  ",
    "  x                                o o    x                              x!!!x     xxx            o        x  ",
    "  x                           xx                                  xxx   xx!!!x    x!!!x          xxx       x  ",
    "  x               x||x        xssssxxx              oo        oo        xx!!!x     xvx          xxxx       x  ",
    "  x              x!!!!x       xxxxxxxxxxxxxxxx oo x xx x oo x xx x oo  xxx!!!x                 xxxxx       x  ",
    "  xsss   @      x!!!!!!x  z   x!!!!!!!!!!!!!!xxxxxx!!!!xxxxxx!!!!xxxxxxx!!!!!x               xxxxxxx       x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                                              ",
    "                                                                                                              "],
  ["                                                                                                          ",
   "                                                                                                          ",
   "                                                                                                          ",
   "                   x     x     x   x    xx   x   xx   x   xxxx  xxxxx   xx                                ",
   " o                  x   x x   x    x    x x  x   x x  x   x     x    x  xx                               o",
   " o o                 x x   x x     x    x  x x   x  x x   xxxx  xxxxx   xx                             o o",
   " o o o                x     x      x    x   xx   x   xx   x     x   x                                o o o",
   " o o o o              x     x      x    x    x   x    x   xxxx  x    x  xx                         o o o o",
   " o o o o o                                                                                       o o o o o",
   " o o o o o o                                                                                   o o o o o o",
   " o o o o o o o                                                                               o o o o o o o",
   " o o o o o o o o                                                                           o o o o o o o o",
   " o o o o o o o o o                                                                       o o o o o o o o o",
   " o o o o o o o o o o                                                                   o o o o o o o o o o",
   " o o o o o o o o o o o o o o o o o o o o o o o o @ o o o o o o o o o o o o o o o o o o o o o o o o o o o o",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                          ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
